name: Deploy Docker to EC2

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/brainwave:latest
            sudo docker stop brainwave || true
            sudo docker rm brainwave || true
            sudo docker run -d --name brainwave -p 80:80 ${{ secrets.DOCKER_USERNAME }}/brainwave:latest