name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  dockerhub-push:
    name: push the image to dockerhub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: dhanikaa/brainwave:latest
  ec2-push:
    needs: dockerhub-push
    name: deploy using ec2
    runs-on: ubuntu-latest

    steps:
      - name: SSH setup
        run: |
          mkdir -p ~/.sshKey/
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.sshKey/brainwave.pem
          chmod 600 ~/.sshKey/brainwave.pem
      - name: Installing and starting docker
        run: 
          ssh -o StrictHostKeyChecking=no -i ~/.sshKey/brainwave.pem ec2-user@ec2-13-60-46-30.eu-north-1.compute.amazonaws.com "sudo apt-get update && sudo apt-get install -y docker.io && sudo systemctl start docker && sudo systemctl enable docker" || exit 1
      - name: Login to EC2 from dockerhub
        run: 
          ssh -o StrictHostKeyChecking=no -i ~/.sshKey/brainwave.pem ec2-user@ec2-13-60-46-30 "
          sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          " || exit 1
      - name: Run docker image on EC2
        run:
          ssh -o StrictHostKeyChecking=no -i ~/.sshKey/brainwave.pem ec2-user@ec2-13-60-46-30 "
          sudo docker rmi dhanikaa/brainwave:latest
          sudo docker stop brainwave || true &&
          sudo docker rm brainwave || true &&
          sudo docker pull dhanikaa/brainwave:latest &&
          sudo docker run --name brainwave-app -d -p 3000:3000 dhanikaa/brainwave:latest
          " || exit 1